admin_artiste_index:
    path:     /
    defaults: { _controller: "ddaBundleArtisteBundle:Artiste:index" }
    methods:  GET

admin_artiste_new:
    path:     /new
    defaults: { _controller: "ddaBundleArtisteBundle:Artiste:new" }
    methods:  [GET, POST]

admin_artiste_edit:
    path:     /{id}/edit
    defaults: { _controller: "ddaBundleArtisteBundle:Artiste:edit" }
    methods:  [GET, POST]

admin_artiste_delete:
    path:     /{id}/delete
    defaults: { _controller: "ddaBundleArtisteBundle:Artiste:delete" }
    methods:  DELETE

#
#        FRONT
#
artiste_show:
    path:     /{slug}/show
    defaults: { _controller: "ddaBundleArtisteBundle:Artiste:show" }
    methods:  GET