admin_video_index:
    path:     /
    defaults: { _controller: "ddaBundleArtisteBundle:Video:index" }
    methods:  GET

admin_video_show:
    path:     /{id}/show
    defaults: { _controller: "ddaBundleArtisteBundle:Video:show" }
    methods:  GET

admin_video_new:
    path:     /new
    defaults: { _controller: "ddaBundleArtisteBundle:Video:new" }
    methods:  [GET, POST]

admin_video_edit:
    path:     /{id}/edit
    defaults: { _controller: "ddaBundleArtisteBundle:Video:edit" }
    methods:  [GET, POST]

admin_video_delete:
    path:     /{id}/delete
    defaults: { _controller: "ddaBundleArtisteBundle:Video:delete" }
    methods:  DELETE
