# venant des modules
domotiquebundle_domobox_module_flux_json:
    path:     /module/esp8266/post/json/
    defaults: { _controller: "DomotiqueDomoboxBundle:Input:addJson" }
    methods:  [POST]

# home
front_office_homepage:
    path:     /
    defaults: { _controller: "DomotiqueDomoboxBundle:Default:index" }

domotiquebundle_domobox:
    path:     /
    defaults: { _controller: "DomotiqueDomoboxBundle:Default:index" }
programme_tv:
    resource: "@ProgrammeTvBundle/Resources/config/routing.yml"
    prefix:   /

domobox_graphique:
    path:     /graphique
    defaults: { _controller: "DomotiqueDomoboxBundle:Default:graphique" }

# retourne une image
domotiquebundle_domobox_webcam:
    path:     /domobox/output/webcam
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:getWebcam" }

#retourne les valeurs de toute les sondes
domotique_log_sonde:
    path: /log/value
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:getCurrentValueJson" }

#donne la moyenne selont l'unitée et le lieu
domotique_log_moyen:
    path: /log/moyenne/{unit}/{spot}/
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:logMoyenne" }
    methods:  [GET]

#retourne l'heure local
domobox_get_hour:
    path: /flux/hour
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:getCurrentDate" }

domobox_log_graph:
    path: /log/graph/{unit}/
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:logAmCharts" }
    methods:  [GET]

domobox_log_graph_total:
    path: /log/total/graph/
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:logAmChartTotal" }
    methods:  [GET]

#AJAX
#    set une valeur au controleur qui envera au module
domotique_module_set_color:
    path:     /domobox/module/set/
    defaults: { _controller: "DomotiqueDomoboxBundle:Default:setModuleColor" }
    methods:  [POST]

domotique_domobox_scheduledTask:
    resource: "@DomotiqueDomoboxBundle/Resources/config/routing/scheduledTask.yml"

domotique_reseau_snowboy:
    resource: "@DomotiqueDomoboxBundle/Resources/config/routing/snowboy.yml"
    prefix:   /snowboy
