<?php

namespace Domotique\ProgrammeTvBundle\Repository;

/**
 * ProgrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getToday()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProgrammeTvBundle:Programme p WHERE p.start >= :start ORDER BY p.start ASC'
            )
            ->setParameter('start', new \DateTime('today'), \Doctrine\DBAL\Types\Type::DATETIME)
            ->getResult();
    }
    public function getTomorrow()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProgrammeTvBundle:Programme p WHERE p.start >= :start ORDER BY p.start ASC'
            )
            ->setParameter('start', new \DateTime('+1 days'), \Doctrine\DBAL\Types\Type::DATETIME)
            ->getResult();
    }
}
