dda_bundle_artiste_admin_artiste:
    resource: "@ddaBundleArtisteBundle/Resources/config/routing/artiste.yml"
    prefix:   /admin/artiste

dda_bundle_admin_actualitee:
    resource: "@ddaBundleArtisteBundle/Resources/config/routing/actualite.yml"
    prefix:   /admin/artiste/actualite

dda_bundle_admin_video:
    resource: "@ddaBundleArtisteBundle/Resources/config/routing/video.yml"
    prefix:   /admin/artiste/video

dda_bundle_artiste_admin_artiste_dossier:
    resource: "@ddaBundleArtisteBundle/Resources/config/routing/dossier.yml"
    prefix:   /admin/artiste/dossier

dda_bundle_artiste_admin_artiste_texte:
    resource: "@ddaBundleArtisteBundle/Resources/config/routing/texte.yml"
    prefix:   /admin/artiste/texte

dda_bundle_artiste_homepage:
    path:     /
    defaults: { _controller: ddaBundleArtisteBundle:Default:index }
