filter:
    excluded_paths:
        - 'app/*'
        - 'var/*'
        - 'bin/*'
        - 'vendor/*'
        - 'web/*'
        - '*.min.js'
        - '*.min.*.js'
        - '*.js'
checks:
    php: true
    javascript: true
    
coding_style:
    php:
        spaces:
            before_parentheses:
                function_declaration: true
                closure_definition: true

build:
    environment:
        php:
            version: 5.5.25
            ini:
                'date.timezone': 'Europe/Paris'
                'memory_limit': '-1'
    dependencies:
         before:
            - mysql -e "CREATE DATABASE symfony"
            - mysql -e "CREATE TABLE symfony.app__options  (option_id int(11) NOT NULL, option_modifieur_ID int(11) DEFAULT NULL, option_name varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL, option_value varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL, option_updated datetime NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;"

    tests:
        override:
            -
                command: 'php vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
