global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - spec
    - features
    - Fixtures
    - DataFixtures
    - var

exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php

rules:
    composer.dependencies_not_installable:
        enabled: false
    composer.invalid_file:
        enabled: true
    composer.outdated_lock_file:
        enabled: true
    composer.security_issue_in_composer:
        enabled: true
    composer.unfixed_dependency_version:
        enabled: false
    composer.warning:
        enabled: false
    symfony.application_not_bootable:
        enabled: false