language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e 'create database symfony;'
  - mysql -e 'USE symfony;'
  - mysql -e 'CREATE TABLE app__options (id INT NOT NULL);'


install:
  - composer install --no-suggest

before_script:
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:schema:update --force
  - php bin/console fos:user:create test test test --super-admin
  - php bin/console doctrine:migrations:migrate

script:
  - php bin/console cache:clear
  - php vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover
