language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
 # - cd src
 # - git clone https://github.com/llaull/AppBundleX.git
 # - mv  -v AppBundleX/* AppBundle/
 # - cd ../
  - mysql -e 'create database test;'
  - mysql -e 'create database symfony;'

install:
  - composer install

before_script:
  - php bin/console doctrine:schema:create
  - php bin/console fos:user:create test test test --super-admin

script:
  - php vendor/phpunit/phpunit/phpunit

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
