language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e 'create database symfony;'
  - mysql -e 'CREATE TABLE symfony.app__options (nul INT NULL);'

install:
  - composer install --no-suggest

before_script:
  - php bin/console doctrine:schema:update --force
  - php bin/console fos:user:create test test test --super-admin
  - php bin/console doctrine:migrations:migrate

after_script:
  - composer update --no-suggest

script:
  - php vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover

notifications:
  - email: false
