language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e 'create database symfony;'

install:
  - composer install

before_script:
  - php bin/console doctrine:schema:create
  - php bin/console fos:user:create test test test --super-admin
  - php bin/console doctrine:migrations:migrate

script:
  - php vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover
