language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e 'create database symfony;'
  - mysql -e 'CREATE TABLE symfony.app__options  (option_id int(11) NOT NULL, option_modifieur_ID int(11) DEFAULT NULL, option_name varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL, option_value varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL, option_updated datetime NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;'

install:
  - php -d memory_limit=-1 bin/composer install

before_script:
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load -q
  - php bin/console fos:user:create test test test --super-admin
  - php bin/console doctrine:migrations:migrate -n
  - php -d memory_limit=-1 bin/composer update

script:
  - php vendor/phpunit/phpunit/phpunit --colors=always --coverage-clover coverage.clover
  - dir

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  - email: false
