back_office_user_index:
    path:     /admin/user
    defaults: { _controller: BackOfficeBundle:User:index }

back_office_user_new:
    path:     /admin/user/new
    defaults: { _controller: BackOfficeBundle:User:new }

back_office_user_edit:
    path:     /admin/user/{id}/edit
    defaults: { _controller: "BackOfficeBundle:User:edit" }
    methods:  [GET, POST]
