<?php

namespace ddaBundle\ArtisteBundle\Repository;

/**
 * BioCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BioCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
