<?php

namespace ddaBundle\ArtisteBundle\Repository;

/**
 * BioChapeauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BioChapeauRepository extends \Doctrine\ORM\EntityRepository
{
}
