<?php

namespace ddaBundle\ArtisteBundle\Repository;

/**
 * BioElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BioElementRepository extends \Doctrine\ORM\EntityRepository
{
}
