<?php

namespace ddaBundle\ArtisteBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    /*
* return count ddaBundleArtisteBundle:Dossier
*/
    public function getActiveCount()
    {
        return $this->createQueryBuilder('v')
            ->select('COUNT(v)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /*
     * return number ddaBundleArtisteBundle:Dossier active
     */
    public function getNoActiveCount()
    {
        $qb = $this->_em->createQueryBuilder();

        return $qb
            ->select('COUNT(v)')
            ->from('ddaBundleArtisteBundle:Video', 'v')
            ->where($qb->expr()->notIn('v.active', 1))
            ->getQuery()
            ->getSingleScalarResult();
    }
}
