admin_page_statique_index:
    path:     /
    defaults: { _controller: "ddaBundleFrontBundle:Page:index" }
    methods:  GET

#admin_page_statique_show:
#    path:     /{slug}.html
#    defaults: { _controller: "ddaBundleFrontBundle:Page:show" }
#    methods:  GET

admin_page_statique_new:
    path:     /new
    defaults: { _controller: "ddaBundleFrontBundle:Page:new" }
    methods:  [GET, POST]

admin_page_statique_edit:
    path:     /{id}/edit
    defaults: { _controller: "ddaBundleFrontBundle:Page:edit" }
    methods:  [GET, POST]

admin_page_statique_delete:
    path:     /{id}/delete
    defaults: { _controller: "ddaBundleFrontBundle:Page:delete" }
    methods:  DELETE
