_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# WYSIWYG
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@ddaBundleFrontBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr

back_office_homepage:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

AnotherRoute:
    path: /
    defaults:
        _controller: ddaBundleFrontBundle:Default:index
        route: app
        permanent: true # this is for 301


dda_bundle_back:
    resource: "@ddaBundleBackBundle/Resources/config/routing.yml"
    prefix:   /admin


dda_bundle_artiste:
    resource: "@ddaBundleArtisteBundle/Resources/config/routing.yml"
    prefix:   /
