_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# WYSIWYG
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@ddaBundleFrontBundle/Resources/config/routing.yml"
    prefix:   /

back_office_homepage:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

dda_bundle_artiste:
    resource: "@ddaBundleArtisteBundle/Resources/config/routing.yml"
    prefix:   /

dda_bundle_back:
    resource: "@ddaBundleBackBundle/Resources/config/routing.yml"
    prefix:   /admin

