<?php

namespace ddaBundle\FrontBundle\Repository;

/**
 * ActualitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualitesRepository extends \Doctrine\ORM\EntityRepository
{
}
