back_office_homepage:
    path:     /
    defaults: { _controller: BackOfficeBundle:Default:index }

back_office_user:
    resource: "@AppBundleUserBundle/Resources/config/routing/user.yml"

app_bundle_to_do:
    resource: "@AppBundleToDoBundle/Resources/config/routing.yml"
    prefix:   /todo

app_options:
    resource: "@BackOfficeBundle/Resources/config/routing/options.yml"
    prefix:   /options
