admin_domotique_log_index:
    path:     /
    defaults: { _controller: "DomotiqueReseauBundle:Log:index" }
    methods:  GET

admin_domotique_log_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiqueReseauBundle:Log:show" }
    methods:  GET

admin_domotique_log_new:
    path:     /new
    defaults: { _controller: "DomotiqueReseauBundle:Log:new" }
    methods:  [GET, POST]

admin_domotique_log_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomotiqueReseauBundle:Log:edit" }
    methods:  [GET, POST]

admin_domotique_log_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiqueReseauBundle:Log:delete" }
    methods:  DELETE
