domotique_reseau_admin_domotique_emplacement:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/emplacement.yml"
    prefix:   /admin/domotique/emplacement

domotique_reseau_admin_domotique_log:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/log.yml"
    prefix:   /admin/domotique/log

domotique_reseau_admin_domotique_module:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/module.yml"
    prefix:   /admin/domotique/module

domotique_reseau_admin_domotique_module_notify:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/modulenotify.yml"
    prefix:   /admin/domotique/module/notify

domotique_reseau_admin_domotique_sensor_type:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/sensortype.yml"
    prefix:   /admin/domotique/sensor/type

domotique_reseau_admin_domotique_sensor_unit:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/sensorunit.yml"
    prefix:   /admin/domotique/sensor/unit
