twig:
    globals:
        BackMenuBadge: '@dda_bundle_back.menubadge'

liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        artiste_categorie :
            quality : 90
            filters :
                relative_resize: { heighten: 173 }
