twig:
    globals:
        BackMenuBadge: '@dda_bundle_back.menubadge'
        AlphabetBar: '@dda_bundle_front.alphabetBar'

liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        artiste_categorie :
            quality : 90
            filters :
                relative_resize: { heighten: 173 }
        artiste_categorie_accueil :
            quality : 90
            filters :
                relative_resize: { heighten: 76 }

assetic:
    assets:
        AbelRegular-eot:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/abel-regular-webfont.eot'
            output: 'Resources/public/font/abel-regular-webfont.eot'
        AbelRegular-svg:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/abel-regular-webfont.svg'
            output: 'Resources/public/font/abel-regular-webfont.svg'
        AbelRegular-ttf:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/abel-regular-webfont.ttf'
            output: 'Resources/public/font/abel-regular-webfont.ttf'
        AbelRegular-woff:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/abel-regular-webfont.woff'
            output: 'Resources/public/font/abel-regular-webfont.woff'

        OvoRegular-eot:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/ovo-regular-webfont.eot'
            output: 'Resources/public/font/ovo-regular-webfont.eot'
        OvoRegular-svg:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/ovo-regular-webfont.svg'
            output: 'Resources/public/font/ovo-regular-webfont.svg'
        OvoRegular-ttf:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/ovo-regular-webfont.ttf'
            output: 'Resources/public/font/ovo-regular-webfont.ttf'
        OvoRegular-woff:
            inputs: '%kernel.root_dir%/../src/ddaBundle/BackBundle/Resources/public/font/ovo-regular-webfont.woff'
            output: 'Resources/public/font/ovo-regular-webfont.woff'
#