frond_office_homepage:
    path:     /index.html
    defaults: { _controller: ddaBundleFrontBundle:Default:index }

front_office_homepage:
    path:     /index.html
    defaults: { _controller: ddaBundleFrontBundle:Default:index }