front_office_homepage:
    path:     /index.html
    defaults: { _controller: ddaBundleFrontBundle:Default:index }

# page
# dossiers-d-artistes.html
# qui liste tous les artistes publier
dda_bundle_front_artiste_all:
    path:     /dossiers-d-artistes.html
    defaults: { _controller: "ddaBundleFrontBundle:Artiste:showAll" }
    methods:  GET


# affiche un dossier d'artiste
# via le slug de l'artiste
dda_bundle_front_artiste_accueil:
    path:     /{slug}/
    defaults: { _controller: "ddaBundleFrontBundle:Artiste:show" }
    methods:  GET

# affiche un dossier d'artiste
# via le slug de l'artiste
dda_bundle_front_artiste_dossier:
    path:     /{artiste}/{dossier}.html
    defaults: { _controller: "ddaBundleFrontBundle:Dossier:showDossier" }
    methods:  GET

# affiche un dossier d'artiste
# via le slug de l'artiste
dda_bundle_front_artiste_dossier_enfant:
    path:     /{artiste}/{parent}/{dossier}.html
    defaults: { _controller: "ddaBundleFrontBundle:Dossier:showDossierEnfant" }
    methods:  GET



front_office_artiste_sss:
    path:     /ajax/artiste/find/byName/{lettre}/
    defaults: { _controller: "ddaBundleFrontBundle:Artiste:showByName" }
    methods:  GET

front_office_page_statique_show:
    path:     /{slug}.html
    defaults: { _controller: "ddaBundleFrontBundle:Default:allPage" }
    methods:  GET

dda_bundle_front_admin_page_statique:
    resource: "@ddaBundleFrontBundle/Resources/config/routing/page.yml"
    prefix:   /admin/page/statique

dda_bundle_front_admin_dda_actualite:
        resource: "@ddaBundleFrontBundle/Resources/config/routing/actualite.yml"
        prefix:   /admin/dda/actualite

dda_bundle_front_artiste:
    resource: "@ddaBundleFrontBundle/Resources/config/routing/artiste.yml"
    prefix:   /

front_office_video:
    path:     /entretiens-video.html
    defaults: { _controller: ddaBundleFrontBundle:Default:allVideo }


