<?php

namespace ddaBundle\ArtisteDossierBundle\Repository;

/**
 * DossierPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierPageRepository extends \Doctrine\ORM\EntityRepository
{
}
