admin_artiste_dossier_categorie_index:
    path:     /
    defaults: { _controller: "ArtisteDossierBundle:Category:index" }
    methods:  GET

admin_artiste_dossier_categorie_show:
    path:     /{id}/show
    defaults: { _controller: "ArtisteDossierBundle:Category:show" }
    methods:  GET

admin_artiste_dossier_categorie_new:
    path:     /new
    defaults: { _controller: "ArtisteDossierBundle:Category:new" }
    methods:  [GET, POST]

admin_artiste_dossier_categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "ArtisteDossierBundle:Category:edit" }
    methods:  [GET, POST]

admin_artiste_dossier_categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "ArtisteDossierBundle:Category:delete" }
    methods:  DELETE
