admin_artiste_dossier_page_index:
    path:     /
    defaults: { _controller: "ArtisteDossierBundle:DossierPage:index" }
    methods:  GET

admin_artiste_dossier_page_show:
    path:     /{id}/show
    defaults: { _controller: "ArtisteDossierBundle:DossierPage:show" }
    methods:  GET

admin_artiste_dossier_page_new:
    path:     /new
    defaults: { _controller: "ArtisteDossierBundle:DossierPage:new" }
    methods:  [GET, POST]

admin_artiste_dossier_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "ArtisteDossierBundle:DossierPage:edit" }
    methods:  [GET, POST]

admin_artiste_dossier_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "ArtisteDossierBundle:DossierPage:delete" }
    methods:  DELETE
